server:
  port: 8380

spring:
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    enabled: true

  mail:
    #네이버로 보내는 경우
#    host: smtp.naver.com
#    port: 465
#    username: 네이버 아이디
#    password: 네이버 smtp 비밀번호
#    protocol: smtps
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#          ssl:
#            enable: true
#            trust: smtp.naver.com

    #구글로 보내는 경우
    host: smtp.gmail.com
    port: 587
    username: #구글계정
    password: #보안2단계 강화하면 나오는 비밀번호
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true